pluginManagement { includeBuild('../node_modules/@react-native/gradle-plugin') }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral(); } }
rootProject.name = 'PapeleriaArcoiris'
include ':app'
includeBuild('../node_modules/@react-native/gradle-plugin')
