import React, { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { PasosTramite } from '../../../components/PasosTramite';
import { SelectorImagen } from '../../../components/SelectorImagen';
import { VistaAntesDespues } from '../../../components/VistaAntesDespues';
import { generarPDF } from '../../../utils/pdfUtils';
import { colors, spacing, typography } from '../../../theme';

export default function EscaneoPDF({ navigation }: any) {
  const [paginas,setPaginas]=useState<string[]>([]); const [procesadas,setProcesadas]=useState<string[]>([]); const [paso,setPaso]=useState(1); const [generando,setGenerando]=useState(false); const [pdfUri,setPdfUri]=useState<string|null>(null);
  const reiniciar=()=>{setPaginas([]);setProcesadas([]);setPaso(1);setPdfUri(null);navigation.navigate('Home');};
  const procesar=async()=>{if(!paginas.length)return Alert.alert('Agrega páginas','Necesitamos al menos una página.');setGenerando(true);await new Promise(r=>setTimeout(r,500));setProcesadas(paginas);setGenerando(false);setPaso(3);};
  const mover=(i:number,d:number)=>setProcesadas(p=>{const n=[...p],t=i+d;if(t<0||t>=n.length)return p;[n[i],n[t]]=[n[t],n[i]];return n;});
  const crearPDF=async()=>{setGenerando(true);try{setPdfUri(await generarPDF(procesadas,{nombre:`escaneo-arcoiris-${Date.now()}`}));}catch{Alert.alert('No se pudo crear el PDF','Revisa las páginas e inténtalo nuevamente.');}finally{setGenerando(false);}};
  return <ScrollView contentContainerStyle={styles.container}><Text style={styles.title}>🗂️ Escaneo múltiple a PDF</Text><PasosTramite pasoActual={paso} onReiniciar={reiniciar}/>
    {paso===1&&<View><Text style={styles.help}>Paso 1. Agrega todas las páginas.</Text><SelectorImagen multiple imagenes={paginas} onCambiar={setPaginas}/><Text style={styles.counter}>📄 {paginas.length} página(s)</Text><Pressable style={styles.primary} onPress={()=>paginas.length?setPaso(2):Alert.alert('Agrega páginas','Necesitamos al menos una página.')}><Text style={styles.primaryText}>Continuar →</Text></Pressable></View>}
    {paso===2&&<View><Text style={styles.help}>Paso 2. Preparamos las páginas para facilitar su lectura.</Text><View style={styles.info}><Text style={styles.infoText}>✨ Nitidez{`\n`}✨ Corrección de perspectiva{`\n`}✨ Contraste{`\n`}✨ Reducción de ruido</Text></View><Pressable style={styles.primary} onPress={procesar}><Text style={styles.primaryText}>✨ Preparar páginas</Text></Pressable></View>}
    {paso===3&&<View><Text style={styles.help}>Paso 3. Revisa y acomoda el orden.</Text>{procesadas.map((_,i)=><View key={i} style={styles.row}><Text style={styles.page}>📄 Página {i+1}</Text><Pressable onPress={()=>mover(i,-1)} disabled={!i} style={styles.small}><Text>⬆️</Text></Pressable><Pressable onPress={()=>mover(i,1)} disabled={i===procesadas.length-1} style={styles.small}><Text>⬇️</Text></Pressable></View>)}<Pressable style={styles.primary} onPress={()=>setPaso(4)}><Text style={styles.primaryText}>✅ Confirmar orden</Text></Pressable><VistaAntesDespues originales={paginas} procesadas={procesadas} onConfirmar={()=>setPaso(4)} onReintentar={()=>setPaso(2)}/></View>}
    {paso===4&&!pdfUri&&<View><Text style={styles.help}>Paso 4. Uniremos todas las páginas en un solo PDF.</Text><View style={styles.info}><Text style={styles.infoText}>📄 {procesadas.length} páginas{`\n`}📐 Tamaño carta{`\n`}🔢 Orden confirmado</Text></View><Pressable style={styles.primary} onPress={crearPDF}><Text style={styles.primaryText}>📄 Generar PDF</Text></Pressable></View>}
    {pdfUri&&<View><Text style={styles.resultTitle}>🎉 ¡Escaneo terminado!</Text><Text style={styles.path}>{pdfUri}</Text><Pressable style={styles.primary} onPress={()=>Alert.alert('PDF listo','El PDF fue generado correctamente.')}><Text style={styles.primaryText}>📤 Compartir PDF</Text></Pressable><Pressable style={styles.secondary} onPress={reiniciar}><Text style={styles.secondaryText}>🔄 Nuevo trámite</Text></Pressable></View>}
    {generando&&<View style={styles.loading}><ActivityIndicator size="large" color={colors.primary}/><Text style={styles.loadingText}>Un momento…</Text></View>}
  </ScrollView>;
}
const styles=StyleSheet.create({container:{padding:spacing.md,paddingBottom:50,backgroundColor:colors.background,flexGrow:1},title:{fontSize:typography.title,fontWeight:'900',color:colors.text},help:{fontSize:typography.body,lineHeight:27,color:colors.text,marginVertical:spacing.md},counter:{fontSize:18,fontWeight:'800',color:colors.success,marginTop:12},primary:{minHeight:60,borderRadius:18,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',marginTop:16},primaryText:{color:'#FFF',fontSize:18,fontWeight:'900'},secondary:{minHeight:60,borderRadius:18,borderWidth:2,borderColor:colors.primary,alignItems:'center',justifyContent:'center',marginTop:12},secondaryText:{color:colors.primary,fontSize:18,fontWeight:'900'},info:{backgroundColor:'#F3F4F6',borderRadius:18,padding:20},infoText:{fontSize:18,lineHeight:32,color:colors.text,fontWeight:'600'},row:{flexDirection:'row',alignItems:'center',backgroundColor:'#FFF',borderRadius:14,padding:10,marginBottom:8},page:{flex:1,fontSize:18,fontWeight:'700',color:colors.text},small:{width:48,height:48,alignItems:'center',justifyContent:'center',borderRadius:12,backgroundColor:'#F3F4F6',marginLeft:6},resultTitle:{fontSize:26,fontWeight:'900',color:colors.success,marginTop:16},path:{fontSize:14,color:colors.muted,marginTop:8},loading:{alignItems:'center',marginTop:20},loadingText:{fontSize:18,color:colors.muted,marginTop:8}});
